# Generated by Django 6.0.3 on 2026-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='licencia_manejo',
            field=models.ImageField(blank=True, null=True, upload_to='maestros/licencias/'),
        ),
    ]
